#! /bin/sh
set -e

rm -rf config

OPTS=
# BINARY_IMAGES=none
BINARY_IMAGES=iso-hybrid
SYSLINUX_THEME=kodibuntu

if [ -n "$APT_HTTP_PROXY" ]; then
	OPTS="${OPTS:+$OPTS }--apt-http-proxy $APT_HTTP_PROXY"
fi
if [ -n "$APT_FTP_PROXY" ]; then
	OPTS="${OPTS:+$OPTS }--apt-ftp-proxy $APT_FTP_PROXY"
fi

if [ -n "$SDK_CHROOTSHELL" ]; then
	OPTS="${OPTS:+$OPTS } --interactive shell"
fi

if [ -n "$SDK_EXT2ROOTFS" ]; then
	OPTS="${OPTS:+$OPTS } --chroot-filesystem ext2"
fi

SDK_ARCH="i386"
if [ -n "$SDK_BUILDx86_64" ]; then
       SDK_ARCH="amd64"
fi

#	--debootstrap-options "--keyring=ubuntu-keyring" \

lb config noauto \
	--mode ubuntu \
	--distribution trusty \
	--architecture $SDK_ARCH \
	--parent-archive-areas "main restricted universe multiverse" \
	--binary-images "$BINARY_IMAGES" \
	--bootloader syslinux \
	--memtest none \
	--source false \
	--security true \
	--iso-application KODIbuntu \
	--iso-volume KODIbuntu \
	--iso-publisher http://kodi.tv \
	--build-with-chroot true \
	$OPTS


#workaround for Bug#622838 syslinux-live and hdd images
if [ "$BINARY_IMAGES" = "hdd" ] ; then
        THISDIR=$(pwd)
        mkdir -p Files/config/includes.chroot/usr/share/syslinux/themes/ubuntu-trusty/isolinux-live
        cd Files/config/includes.chroot/usr/share/syslinux/themes/ubuntu-trusty/
        ln -s isolinux-live syslinux-live
        cd isolinux-live
        ln -s isolinux.cfg syslinux.cfg
        cd $THISDIR
fi

# Copy additional config files to config tree
cp -R configFiles/* config
