directory = new Object()
directory['en_GB'] = new Object()
directory['en_GB']['accessibility.html'] = true
directory['en_GB']['browse.html'] = true
directory['en_GB']['gethelp.html'] = true
directory['en_GB']['mobilise.html'] = true
directory['en_GB']['music.html'] = true
directory['en_GB']['office.html'] = true
directory['en_GB']['photos.html'] = true
directory['en_GB']['social.html'] = true
directory['en_GB']['usc.html'] = true
directory['en_GB']['welcome.html'] = true
directory['uk'] = new Object()
directory['uk']['accessibility.html'] = true
directory['uk']['browse.html'] = true
directory['uk']['gethelp.html'] = true
directory['uk']['mobilise.html'] = true
directory['uk']['music.html'] = true
directory['uk']['office.html'] = true
directory['uk']['photos.html'] = true
directory['uk']['social.html'] = true
directory['uk']['usc.html'] = true
directory['uk']['welcome.html'] = true
