Welcome to Debian GNU/Linux!

This is a Debian Live CDROM,
built on LB_DATE.

The default option is 'live'.

If the system fails to boot at all (the typical
symptom is a white screen which doesn't go away),
append 'video=ofonly' or use 'live-failsafe'.

The plain options are for the powerpc family of
processors (from 601 to G4). The *64 options are for
64bit powerpc processors, which include the IBM
Power3, Power4, Power5, ... boxes, as well as the
Apple G5 boxes. Press the tab key for a list of
options, or type 'help' for help.

************************************
If in doubt, just press enter, and if that
doesn't work, try 'live video=ofonly'.
************************************
