#!/bin/sh -e

set -e

if dpkg-maintscript-helper supports mv_conffile 2>/dev/null; then
    dpkg-maintscript-helper mv_conffile /etc/xdg/pcmanfm/xbmcbuntu.conf /etc/xdg/pcmanfm/xbmcbuntu/pcmanfm.conf 0.15 -- "$@"
fi

case "$1" in
  remove|purge)
    if [ -x /usr/lib/lightdm/lightdm-set-defaults ] ; then
      /usr/lib/lightdm/lightdm-set-defaults --remove --session=XBMC || true
      /usr/lib/lightdm/lightdm-set-defaults --remove --greeter=lightdm-gtk-greeter || true
    fi
    ;;
esac


#DEBHELPER#
exit 0
