.TH LIVE\-BUILD 1 2011\-10\-30 3.0~a38-1 "Debian Live Project"

.SH NAME
\fBlb source_iso\fR \- Complete the source stage

.SH SYNOPSIS
\fBlb source_iso\fR [\fIlive\-build options\fR]

.SH DESCRIPTION
\fBlb source_iso\fR is a low\-level command (plumbing) of \fIlive\-build\fR(7), the Debian Live tool suite.
.PP
.\" FIXME

.SH OPTIONS
\fBlb source_iso\fR has no specific options but understands all generic live\-build options. See \fIlive\-build\fR(7) for a complete list of all generic live\-build options.

.SH FILES
.\" FIXME
.IP "\fBn/a\fR" 4

.SH SEE ALSO
\fIlive\-build\fR(7)
.PP
This program is a part of live\-build.

.SH HOMEPAGE
More information about live\-build and the Debian Live project can be found on the homepage at <\fIhttp://live.debian.net/\fR> and in the manual at <\fIhttp://live.debian.net/manual/\fR>.

.SH BUGS
Bugs can be reported by submitting a bugreport for the live\-build package in the Debian Bug Tracking System at <\fIhttp://bugs.debian.org/\fR> or by writing a mail to the Debian Live mailing list at <\fIdebian-live@lists.debian.org\fR>.

.SH AUTHOR
live\-build was written by Daniel Baumann <\fIdaniel@debian.org\fR> for the Debian project.
